name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics-top-spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: philpinsdorf
          template: classic
          base: ""
          config_timezone: Europe/Berlin
          plugin_music: yes
          plugin_music_limit: 10
          plugin_music_time_range: medium
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_user: rexituz
          plugin_music_token: ${{ secrets.MUSIC_TOKEN }}
          
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
