name: Metrics
on:
  # Schedule updates
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics-top-spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: philpinsdorf
          template: classic
          base: ""
          config_timezone: Europe/Berlin
          filename: metrics.plugin.music.svg
          plugin_music: yes
          plugin_music_limit: 10
          plugin_music_time_range: short
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_user: rexituz
          plugin_music_token: ${{ secrets.MUSIC_TOKEN }}
